version: '3.5'
services:
  readme.files.mongo:
    image: mongo
    restart: always
    container_name: readme.files.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-files

    ports:
      - 27018:27017

    volumes:
      - readme.mongo.files:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-files --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.files.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.files.mongo.ui
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.files.mongo:27017/

volumes:
  readme.mongo.files:
